My Project: app.ImagePreprocessing Namespace Reference
app.ImagePreprocessing Namespace Reference
Functions
getAdvancedFeatures (imageIn)
avgGray (image)
avgRed (image)
avgGreen (image)
avgBlue (image)
numBrownRed (image)
numBrownGreen (image)
numBrownBlue (image)
FdHuMoments (image)
FdHaralick (image)
FdHistogram (image, mask=None, bins=8)
allFilesInDir (dir_name, label)
allSetFiles (self, setListPath, dir_name, label)
generateDataFromFolder (set_list_path_healthy, set_list_path_blighted, folder_name_healthy, folder_name_blighted, isTraining, outDir)
generate_data_from_sets (folder_name, healthy_set_path, blighted_set_path, isTraining, outDir)
Detailed Description
Created on Sat Feb  8 11:20:09 2020
@author: Donovan
Function Documentation
allFilesInDir()
app.ImagePreprocessing.allFilesInDir (dir_name, label)
References app.ImagePreprocessing.avgBlue(), app.ImagePreprocessing.avgGray(), app.ImagePreprocessing.avgGreen(), app.ImagePreprocessing.avgRed(), app.ImagePreprocessing.FdHaralick(), app.ImagePreprocessing.FdHuMoments(), app.ImagePreprocessing.getAdvancedFeatures(), app.ImagePreprocessing.numBrownBlue(), app.ImagePreprocessing.numBrownGreen(), and app.ImagePreprocessing.numBrownRed().
Referenced by app.ImagePreprocessing.generate_data_from_sets(), and app.ImagePreprocessing.generateDataFromFolder().
allSetFiles()
app.ImagePreprocessing.allSetFiles (self, setListPath, dir_name, label)
Referenced by app.ImagePreprocessing.generate_data_from_sets().
avgBlue()
app.ImagePreprocessing.avgBlue (image)
Referenced by app.ImagePreprocessing.allFilesInDir().
avgGray()
app.ImagePreprocessing.avgGray (image)
Referenced by app.ImagePreprocessing.allFilesInDir().
avgGreen()
app.ImagePreprocessing.avgGreen (image)
Referenced by app.ImagePreprocessing.allFilesInDir().
avgRed()
app.ImagePreprocessing.avgRed (image)
Referenced by app.ImagePreprocessing.allFilesInDir().
FdHaralick()
app.ImagePreprocessing.FdHaralick (image)
Referenced by app.ImagePreprocessing.allFilesInDir().
FdHistogram()
app.ImagePreprocessing.FdHistogram (image, mask = None, bins = 8)
Extracts color histogram feature from an image
Parameters
----------
image : imread
    The image used for feature extraction
Returns
-------
Feature : Float Array
    The color histogram in the image.
Reference
---------
https://gogul.dev/software/image-classification-python
FdHuMoments()
app.ImagePreprocessing.FdHuMoments (image)
Extracts Hu moments feature from an image
Parameters
----------
image : imread
    The image used for feature extraction
Returns
-------
Feature : Float Array
    The Hu moments in the image.
Reference
---------
https://gogul.dev/software/image-classification-python
Referenced by app.ImagePreprocessing.allFilesInDir().
generate_data_from_sets()
app.ImagePreprocessing.generate_data_from_sets (folder_name, healthy_set_path, blighted_set_path, isTraining, outDir)
References app.ImagePreprocessing.allFilesInDir(), and app.ImagePreprocessing.allSetFiles().
generateDataFromFolder()
app.ImagePreprocessing.generateDataFromFolder (set_list_path_healthy, set_list_path_blighted, folder_name_healthy, folder_name_blighted, isTraining, outDir)
References app.ImagePreprocessing.allFilesInDir().
getAdvancedFeatures()
app.ImagePreprocessing.getAdvancedFeatures (imageIn)
Returns a tuple of advanced features.
Parameters
----------
imageIn : Image
    The image to process.
Returns
-------
returnValues : tuple
    numbers.
Referenced by app.ImagePreprocessing.allFilesInDir().
numBrownBlue()
app.ImagePreprocessing.numBrownBlue (image)
Referenced by app.ImagePreprocessing.allFilesInDir().
numBrownGreen()
app.ImagePreprocessing.numBrownGreen (image)
Referenced by app.ImagePreprocessing.allFilesInDir().
numBrownRed()
app.ImagePreprocessing.numBrownRed (image)
Referenced by app.ImagePreprocessing.allFilesInDir().