My Project: app.ML_Class_New.Active_ML_Model Class Reference
app.ML_Class_New.Active_ML_Model Class Reference
Public Member Functions
__init__ (self, ml_classifier, preprocess, data, token, modeldir, tempdir, n_samples=10)
train_model_add (self, sample)
next_samples (self, sampling_method, n_samples=5)
Public Member Functions inherited from app.ML_Class_New.ML_Model
get_x (self, data)
get_y (self, data)
train_model (self, data)
set_token (self, token)
get_token (self)
GetKnownPredictions (self, new_data)
GetUnknownPredictions (self, new_data_X)
K_fold (self)
infoForProgress (self)
infoForResults (self, test)
save_model (self)
tempsave_model (self)
clear_tempdata (self)
visualize_model (self, maxdepth)
Public Attributes
sample
test
train
Public Attributes inherited from app.ML_Class_New.ML_Model
modeldir
tempdir
train_files
labels
hastrained
is_finalized
ml_classifier
preprocess
X
Y
ml_model
token
Detailed Description
This class creates an active learning model based on the data sent,
data preprocessing, and type of ml classifier.
Constructor & Destructor Documentation
__init__()
app.ML_Class_New.Active_ML_Model.__init__ (self, ml_classifier, preprocess, data, token, modeldir, tempdir, n_samples = 10)
This function controls the initial creation of the machine learning model.
Parameters
----------
train_data : pandas DataFrame
    The data the machine learning model will be built on.
ml_classifier : classifier object
    The classifier to be used to create the machine learning model.
preprocess : Python Function
    The function used to preprocess the data before model creation.
Attributes
-------
ml_classifier : classifier object
    The classifier to be used to create the machine learning model.
preprocess : Python Function
    The function used to preprocess the data before model creation.
X : pandas DataFrame
    The features in the train set.
y : pandas Series
    The responce variable.
ml_model : fitted machine learning classifier
    The machine learning model created using the training data.
Reimplemented from app.ML_Class_New.ML_Model.
References app.ML_Class_New.Active_ML_Model.__init__().
Referenced by app.ML_Class_New.Active_ML_Model.__init__().
Member Function Documentation
next_samples()
app.ML_Class_New.Active_ML_Model.next_samples (self, sampling_method, n_samples = 5)
References app.ML_Class_New.ML_Model.ml_model, app.ML_Class_New.Active_ML_Model.sample, and app.ML_Class_New.Active_ML_Model.test.
train_model_add()
app.ML_Class_New.Active_ML_Model.train_model_add (self, sample)
References app.ML_Class_New.Active_ML_Model.train, and app.ML_Class_New.ML_Model.train_model().
Member Data Documentation
sample
app.ML_Class_New.Active_ML_Model.sample
Referenced by app.ML_Class_New.Active_ML_Model.next_samples().
test
app.ML_Class_New.Active_ML_Model.test
Referenced by app.ML_Class_New.Active_ML_Model.next_samples().
train
app.ML_Class_New.Active_ML_Model.train
Referenced by app.ML_Class_New.Active_ML_Model.train_model_add().
The documentation for this class was generated from the following file:
app/ML_Class_New.py