My Project: app.web Namespace Reference
app.web Namespace Reference
Functions
load_paths ()
getData ()
createMLModel (data, doTrain)
prepare_loadedModel (al_model)
renderLabel (form)
initializeAL (form, confidence_break=.85)
getNextSetOfImages (form, sampling_method)
prepairResults (form, train)
redirect_to_index ()
home ()
load_prev_model ()
ai_explained ()
applicationExplained ()
step1 ()
step2 ()
step3 ()
step4 ()
step5 ()
step6 ()
step4Labeling ()
step5Intermediate ()
save_model ()
clear_model ()
tree_img (filename, istree)
step5Final ()
step6Feedback (h_list, u_list, h_conf_list, u_conf_list)
Variables
bootstrap = Bootstrap(app)
al_model = None
default_ml_model = None
Detailed Description
@package web
This method is responsible for the inner workings of the different web pages in this application.
Function Documentation
ai_explained()
app.web.ai_explained ()
applicationExplained()
app.web.applicationExplained ()
Operates the applicationExplained.html web page.
clear_model()
app.web.clear_model ()
Clears the existing model in session if it exist
createMLModel()
app.web.createMLModel (data, doTrain)
Prepares the training set and creates a machine learning model using the training set.
Parameters
----------
data : Pandas DataFrame
    The data that contains the features for each image
Returns
-------
ml_model : ML_Model class object
    ml_model created from the training set.
train_img_names : String
    The names of the images.
Referenced by app.web.getNextSetOfImages(), and app.web.prepairResults().
getData()
app.web.getData ()
Gets and returns the csvOut.csv as a DataFrame.
Returns
-------
data : Pandas DataFrame
    The data that contains the features for each image.
Referenced by app.web.getNextSetOfImages(), app.web.initializeAL(), and app.web.prepairResults().
getNextSetOfImages()
app.web.getNextSetOfImages (form, sampling_method)
Uses a sampling method to get the next set of images needed to be labeled.
Parameters
----------
form : LabelForm class object
    form to be used when displaying label.html
sampling_method : SamplingMethods Function
    function that returns the queue and the new test set that does not contain the queue.
Returns
-------
render_template : flask function
    renders the label.html webpage.
References app.web.createMLModel(), app.web.getData(), and app.web.renderLabel().
Referenced by app.web.step4Labeling().
home()
app.web.home ()
Operates the root (/) and index(index.html) web pages.
References app.web.load_paths().
initializeAL()
app.web.initializeAL (form, confidence_break = .85)
Initializes the active learning model and sets up the webpage with everything needed to run the application.
Parameters
----------
form : LabelForm class object
    form to be used when displaying label.html
confidence_break : number
    How confident the model is.
Returns
-------
render_template : flask function
    renders the label.html webpage.
References app.web.getData(), and app.web.renderLabel().
Referenced by app.web.step4Labeling().
load_paths()
app.web.load_paths ()
Referenced by app.web.home(), app.web.load_prev_model(), and app.web.renderLabel().
load_prev_model()
app.web.load_prev_model ()
Loads the previous model based on the token enter on the given form.
If the model exist then it will be loaded, otherwise it will be checked if its already model through the is_locked method
or if the model is not found it will return a not found message
References app.web.load_paths(), app.web.prepairResults(), and app.web.prepare_loadedModel().
prepairResults()
app.web.prepairResults (form, train)
Creates the new machine learning model and gets the confidence of the machine learning model.
Parameters
----------
form : LabelForm class object
    form to be used when displaying label.html
Returns
-------
render_template : flask function
    renders the appropriate webpage based on new confidence score.
References app.web.createMLModel(), and app.web.getData().
Referenced by app.web.load_prev_model(), and app.web.step4Labeling().
prepare_loadedModel()
app.web.prepare_loadedModel (al_model)
Referenced by app.web.load_prev_model().
redirect_to_index()
app.web.redirect_to_index ()
renderLabel()
app.web.renderLabel (form)
prepairs a render_template to show the label.html web page.
Parameters
----------
form : LabelForm class object
    form to be used when displaying label.html
Returns
-------
render_template : flask function
    renders the label.html webpage.
References app.web.load_paths().
Referenced by app.web.getNextSetOfImages(), app.web.initializeAL(), and app.web.step4Labeling().
save_model()
app.web.save_model ()
saves the model that is currently in session
step1()
app.web.step1 ()
Operates the step1.html web page.
step2()
app.web.step2 ()
Operates the step2.html web page.
step3()
app.web.step3 ()
Operates the step3.html web page.
step4()
app.web.step4 ()
Operates the step4.html web page.
step4Labeling()
app.web.step4Labeling ()
Operates the step4Labeling.html web page.
Where Labeling of Leaf as Healthy/Unhealthy Happens.
References app.web.getNextSetOfImages(), app.web.initializeAL(), app.web.prepairResults(), and app.web.renderLabel().
step5()
app.web.step5 ()
Operates the step5.html web page.
step5Final()
app.web.step5Final ()
Operates the step5.html web page.
step5Intermediate()
app.web.step5Intermediate ()
Operates the step5.html web page.
step6()
app.web.step6 ()
Operates the step6.html web page.
step6Feedback()
app.web.step6Feedback (h_list, u_list, h_conf_list, u_conf_list)
Operates the step6Feedback.html web page.
tree_img()
app.web.tree_img (filename, istree)
Allows the tree image to be viewable in the web app when passed.
Variable Documentation
al_model
app.web.al_model = None
bootstrap
app.web.bootstrap = Bootstrap(app)
default_ml_model
app.web.default_ml_model = None